name: Create Kubernetes Cluster
on: push
jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - uses: actions/checkout@v2
    - name: Install Terraform
      id: install-terraform
      run: wget -O terraform.zip https://releases.hashicorp.com/terraform/1.0.7/terraform_1.0.7_linux_amd64.zip && unzip terraform.zip && chmod +x terraform && sudo mv terraform /usr/local/bin
    - name: Apply Terraform
      id: apply-terraform
      run: terraform init && terraform apply -auto-approve -var="project_id=${{ secrets.PROJECT_ID_L15  }}" -var="github_token=${{ secrets.GH_TOKEN_FLUX  }}"
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS_L15 }} 